@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.unascribed.blockrenderer.mixin;

import com.unascribed.blockrenderer.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;