@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.unascribed.blockrenderer.render.request;

import com.unascribed.blockrenderer.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;