@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.unascribed.blockrenderer.proxy;

import com.unascribed.blockrenderer.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;